[package]
name = "sumcheck201playground"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-std.workspace = true
ark-ff.workspace = true
ark-ec.workspace = true
rand.workspace = true
polynomial.workspace = true
fiat_shamir.workspace = true