[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.3"
rand = "0.8.5"
num = { version = "0.4.0", features = [] }
hex = "0.4.3"
sha256 = "1.4.0"