[package]
name = "gkr"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.4.2"
ark-test-curves = {version = "0.4.2", features = ["bls12_381_scalar_field", "bls12_381_curve", "ed_on_bls12_381"]}
polynomial = {path = "../polynomial"}
fiat_shamir = {path = "../fiat_shamir"}