name: Build Program

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Build and Execute
    runs-on:
      - runs-on
      - runner=16cpu-linux-x64
      - run-id=${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.85.0

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version

      - name: Build SP1 program
        run: |
          cd program
          ~/.sp1/bin/cargo-prove prove build

      - name: Execute SP1 program
        run: |
          cargo run --release -- --execute
