[package]
name = "polynomial"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff.workspace = true
ark-test-curves.workspace = true
ark-serialize.workspace = true
digest.workspace = true
ark-std.workspace = true
