[package]
name = "polynomial"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-poly = "0.4.2"
ark-ff = "0.4.2"
ark-test-curves = {version = "0.4.2", features = ["bls12_381_scalar_field", "bls12_381_curve", "ed_on_bls12_381"]}
