[package]
name = "plonk_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff.workspace = true
ark-ec.workspace = true
ark-test-curves.workspace = true
polynomial.workspace = true
fiat_shamir.workspace = true
plonk_core.workspace =  true
circuits.workspace = true
regex = "1.11.0"